services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      - THREADS=${THREADS}
      - DRIVER_MEMORY=${DRIVER_MEMORY}
      - SHUFFLE_PARTITIONS=${SHUFFLE_PARTITIONS}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./:/app/
    depends_on:
      postgres:
        condition: service_started
      ollama:
        condition: service_started
    networks:
      - net
    # keep container running, only for development
    command: tail -f /dev/null

  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - net
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  net:
    driver: bridge
